export type LOAD_COUNTER = 'LOAD_COUNTER';
export const LOAD_COUNTER: LOAD_COUNTER = 'LOAD_COUNTER';
export type LOAD_COUNTER_ERROR = 'LOAD_COUNTER_ERROR';
export const LOAD_COUNTER_ERROR: LOAD_COUNTER_ERROR = 'LOAD_COUNTER_ERROR';
export type LOAD_COUNTER_SUCCESS = 'LOAD_COUNTER_SUCCESS';
export const LOAD_COUNTER_SUCCESS: LOAD_COUNTER_SUCCESS = 'LOAD_COUNTER_SUCCESS';

export type TIMER_START = 'TIMER_START';
export const TIMER_START: TIMER_START = 'TIMER_START';
export type TIMER_TICK = 'TIMER_TICK';
export const TIMER_TICK: TIMER_TICK = 'TIMER_TICK';
export type TIMER_STOP = 'TIMER_STOP';
export const TIMER_STOP: TIMER_STOP = 'TIMER_STOP';

export const TIME_INTERVAL = 1000;

export type LOAD_COUNTER_TYPES = LOAD_COUNTER | LOAD_COUNTER_SUCCESS | LOAD_COUNTER_ERROR;
export type TIMER_TYPES = TIMER_START | TIMER_TICK | TIMER_STOP;