export type LOAD_COUNTER = 'LOAD_COUNTER';
export const LOAD_COUNTER: LOAD_COUNTER = 'LOAD_COUNTER';
export type LOAD_COUNTER_ERROR = 'LOAD_COUNTER_ERROR';
export const LOAD_COUNTER_ERROR: LOAD_COUNTER_ERROR = 'LOAD_COUNTER_ERROR';
export type LOAD_COUNTER_SUCCESS = 'LOAD_COUNTER_SUCCESS';
export const LOAD_COUNTER_SUCCESS: LOAD_COUNTER_SUCCESS = 'LOAD_COUNTER_SUCCESS';

export type LOAD_COUNTER_TYPES = LOAD_COUNTER | LOAD_COUNTER_SUCCESS | LOAD_COUNTER_ERROR;